-- lush port of https://github.com/yasukotelin/shirotelin
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv

---@diagnostic disable: undefined-global
local theme = lush(function(injected_functions)
	local sym = injected_functions.sym
	return {
		Boolean({ gui = "bold", fg = "#0000af" }),
		Character({ fg = "#0000af" }),
		ClassName({ gui = "bold", fg = "#005f5f" }),
		CmpItemKindDefault({ fg = "#af00af" }),
		CmpItemAbbrDeprecatedDefault({ fg = "#005f00" }),
		CmpItemAbbrDeprecated({ CmpItemAbbrDeprecatedDefault }),
		CmpItemKind({ CmpItemKindDefault }),
		ColorColumn({ bg = "lightred" }),
		Comment({ fg = "#005f00" }),
		Conceal({ bg = "darkgrey", fg = "lightgrey" }),
		Conditional({ gui = "bold", fg = "#87005f" }),
		Constant({ gui = "bold", fg = "#0000af" }),
		Cursor({ bg = "fg", fg = "bg" }),
		CursorLine({ gui = "underline" }),
		FoldColumn({ bg = "#a8a8a8", fg = "#00005f" }),
		CursorLineFold({ FoldColumn }),
		CursorLineNr({ gui = "bold", fg = "#444444" }),
		Debug({ gui = "bold", fg = "#af00af" }),
		Define({ gui = "bold", fg = "#00005f" }),
		Delimiter({ gui = "bold", fg = "#af00af" }),
		DiagnosticDeprecated({ gui = "strikethrough", sp = "red" }),
		DiagnosticError({ fg = "red" }),
		DiagnosticHint({ fg = "#0000af" }),
		DiagnosticInfo({ fg = "lightblue" }),
		DiagnosticOk({ fg = "lightgreen" }),
		DiagnosticWarn({ fg = "orange" }),
		DiagnosticFloatingError({ DiagnosticError }),
		DiagnosticFloatingHint({ DiagnosticHint }),
		DiagnosticFloatingInfo({ DiagnosticInfo }),
		DiagnosticFloatingOk({ DiagnosticOk }),
		DiagnosticFloatingWarn({ DiagnosticWarn }),
		DiagnosticSignError({ DiagnosticError }),
		DiagnosticSignHint({ DiagnosticHint }),
		DiagnosticSignInfo({ DiagnosticInfo }),
		DiagnosticSignOk({ DiagnosticOk }),
		DiagnosticSignWarn({ DiagnosticWarn }),
		DiagnosticUnderlineError({ gui = "underline", sp = "red" }),
		DiagnosticUnderlineHint({ gui = "underline", sp = "lightgrey" }),
		DiagnosticUnderlineInfo({ gui = "underline", sp = "lightblue" }),
		DiagnosticUnderlineOk({ gui = "underline", sp = "lightgreen" }),
		DiagnosticUnderlineWarn({ gui = "underline", sp = "orange" }),
		DiagnosticUnnecessary({ Comment }),
		DiagnosticVirtualTextError({ DiagnosticError }),
		DiagnosticVirtualTextHint({ DiagnosticHint }),
		DiagnosticVirtualTextInfo({ DiagnosticInfo }),
		DiagnosticVirtualTextOk({ DiagnosticOk }),
		DiagnosticVirtualTextWarn({ DiagnosticWarn }),
		DiffAdd({ bg = "#c8ffc8" }),
		DiffChange({ bg = "#c8ffc8" }),
		DiffDelete({ bg = "#ffc8c8", fg = "#ffc8c8" }),
		DiffText({ bg = "#60ff87" }),
		Directory({ fg = "#00005f" }),
		EndOfBuffer({ fg = "#0000af" }),
		Error({ gui = "bold", bg = "#ffffff", fg = "#ff0000" }),
		ErrorMsg({ bg = "#ffffff", fg = "#ff0000" }),
		Exception({ gui = "bold", fg = "#87005f" }),
		Float({ fg = "#0000af" }),
		FloatShadow({ blend = 80, bg = "black" }),
		FloatShadowThrough({ blend = 100, bg = "black" }),
		Title({ gui = "bold", fg = "#87005f" }),
		FloatTitle({ Title }),
		FloatWindow({ bg = "#ffffaf" }),
		Folded({ bg = "#dadada", fg = "#00005f" }),
		Function({ gui = "bold", fg = "#00005f" }),
		Identifier({ gui = "bold", fg = "#00005f" }),
		Ignore({ fg = "bg" }),
		IncSearch({ bg = "#cfcca3" }),
		Include({ gui = "bold", fg = "#00005f" }),
		InformationHighlight({ fg = "#9e9e9e" }),
		Keyword({ gui = "bold", fg = "#87005f" }),
		Label({ gui = "bold", fg = "#87005f" }),
		LineNr({ fg = "#545454" }),
		LineNrAbove({ LineNr }),
		LineNrBelow({ LineNr }),
		Macro({ gui = "bold", fg = "#00005f" }),
		MatchBackground({ ColorColumn }),
		MatchParen({ bg = "#ffc7fe" }),
		MatchParenCur({ MatchParen }),
		MatchWord({ MatchParen }),
		ModeMsg({ gui = "bold", fg = "#303030" }),
		MoreMsg({ gui = "bold", fg = "seagreen" }),
		NonText({ fg = "#d0d0d0" }),
		Normal({ bg = "#ffffff", fg = "black" }),
		SignColumn({ Normal }),
		DirBufHash({ Normal }),
		Number({ fg = "#0000af" }),
		Operator({ gui = "bold", fg = "#87005f" }),
		Pmenu({ bg = "#eeeeee" }),
		NormalFloat({ Pmenu }),
		PmenuExtra({ Pmenu }),
		PmenuSel({ bg = "#afd7ff", fg = "#000000" }),
		PmenuExtraSel({ PmenuSel }),
		PmenuKind({ Pmenu }),
		PmenuKindSel({ PmenuSel }),
		PmenuSbar({ bg = "#eeeeee" }),
		PmenuThumb({ bg = "#185858" }),
		PreCondit({ gui = "bold", fg = "#00005f" }),
		PreProc({ gui = "bold", fg = "#00005f" }),
		Question({ gui = "bold", fg = "seagreen" }),
		ReferenceHighlight({ bg = "#d7d7ff" }),
		Repeat({ gui = "bold", fg = "#87005f" }),
		Search({ bg = "#ffff80", fg = "#000000" }),
		QuickFixLine({ Search }),
		SelectLine({ bg = "#ffff80", fg = "#000000" }),
		Special({ gui = "bold", fg = "#af00af" }),
		SpecialChar({ gui = "bold", fg = "#af00af" }),
		SpecialComment({ fg = "#006300" }),
		SpecialKey({ fg = "#008787" }),
		SpellBad({ gui = "undercurl", bg = "#ff0000", sp = "red" }),
		SpellCap({ gui = "undercurl", bg = "#0000af", sp = "blue" }),
		SpellLocal({ gui = "undercurl", bg = "magenta", sp = "darkcyan" }),
		SpellRare({ gui = "undercurl", bg = "darkcyan", sp = "magenta" }),
		Statement({ gui = "bold", fg = "#87005f" }),
		StatusLine({ gui = "bold", bg = "#000087", fg = "#ffffff" }),
		StatusLineNC({ gui = "bold", bg = "#8a8a8a", fg = "#ffffff" }),
		StatusLineTerm({ gui = "bold", bg = "#000087", fg = "#ffffff" }),
		StatusLineTermNC({ gui = "bold", bg = "#8a8a8a", fg = "#ffffff" }),
		StorageClass({ gui = "bold", fg = "#87005f" }),
		String({ fg = "#0000af" }),
		Structure({ gui = "bold", fg = "#87005f" }),
		Substitute({ Search }),
		TabLine({ gui = "underline", bg = "lightgrey" }),
		TabLineFill({ gui = "reverse" }),
		TabLineSel({ gui = "bold" }),
		Tag({ gui = "bold", fg = "#af00af" }),
		TermCursor({ gui = "reverse" }),
		Terminal({ bg = "#ffffff", fg = "#000000" }),
		Todo({ gui = "bold", bg = "#afd7af", fg = "#005f00" }),
		Type({ gui = "bold", fg = "#87005f" }),
		Typedef({ gui = "bold", fg = "#87005f" }),
		Underlined({ gui = "underline", fg = "#af00af" }),
		VertSplit({ fg = "#0000af" }),
		Visual({ bg = "#cde8ff" }),
		VisualNOS({ gui = "bold,underline" }),
		WarningHighlight({ bg = "#ffffd7" }),
		WarningMsg({ fg = "#ff0000" }),
		Whitespace({ NonText }),
		WildMenu({ bg = "yellow", fg = "black" }),
		WinBar({ gui = "bold" }),
		WinBarNC({ WinBar }),

		WinSeparator({ VertSplit }),

		FzfLuaBorder({ Normal }),
		FzfLuaCursor({ Cursor }),
		FzfLuaCursorLine({ CursorLine }),
		FzfLuaCursorLineNr({ CursorLineNr }),
		FzfLuaNormal({ Normal }),
		FzfLuaScrollFloatEmpty({ PmenuSbar }),
		FzfLuaScrollFloatFull({ PmenuThumb }),
		FzfLuaSearch({ IncSearch }),

		LspErrorHighlight({ Error }),
		LspErrorText({ Error }),
		LspHintHighlight({ WarningHighlight }),
		LspHintText({ WarningHighlight }),
		LspInfoBorder({ Label }),
		LspInfoFiletype({ Type }),
		LspInfoList({ Function }),
		LspInfoTip({ Comment }),
		LspInfoTitle({ Title }),
		LspInformationHighlight({ InformationHighlight }),
		LspInformationText({ Normal }),
		LspWarningHighlight({ WarningHighlight }),
		LspWarningText({ WarningHighlight }),
	}
end)
return theme
