-- yeah. no.
return {}

-- return {
-- 	{
-- 		"rgzntrade/codeium.nvim",
-- 		dependencies = {
-- 			"nvim-lua/plenary.nvim",
-- 			"hrsh7th/nvim-cmp",
-- 		},
-- 		config = function()
-- 			require("codeium").setup({})
-- 		end,
-- 	},
-- 	{
-- 		"zbirenbaum/copilot.lua",
-- 		config = function()
-- 			require("copilot").setup({
-- 				suggestion = { enabled = false },
-- 				panel = { enabled = false },
-- 			})
-- 		end,
-- 	},
-- 	{
-- 		"zbirenbaum/copilot-cmp",
-- 		config = function()
-- 			require("copilot_cmp").setup()
-- 		end,
-- 	},
-- }
