#!/usr/bin/env bash
xsetroot -cursor_name left_ptr

feh --bg-fill /home/hq1/.wallpaper.jpg &

autostart() {
  pgrep -u "$USER" -f "$1" || $1 &
}

autostart "dunst"
autostart "btops"
autostart "picom --config /home/hq1/.config/picom.conf"
autostart "screensaver.sh"
autostart "sxhkd"
autostart "greenclip daemon"
autostart "flameshot"
autostart "polybar example"
autostart "trackpoint"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           0
bspc config top_padding          50

bspc config normal_border_color "#000000"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true

bspc rule -a Zathura state=tiled
bspc rule -a FloatThis state=floating
bspc rule -a feh state=floating center=true
