#!/usr/bin/env bash
xsetroot -cursor_name left_ptr

autostart() {
  pgrep -u "$USER" -f "$1" || $1 &
}

autostart-kill() {
  pkill -u "$USER" "$1"; $1 &
}

autostart "firefox"
autostart "dunst"
autostart "picom -b --config /home/hq1/.config/picom.conf"
autostart "screensaver.sh"
autostart "sxhkd"
autostart "greenclip daemon"
autostart "flameshot"
autostart "polybar example"
autostart "trackpoint"
autostart "bspi_listen --config /home/hq1/.config/bspwm/bspi.ini"
autostart "udiskie -t"
autostart "wallpaper"
autostart "conky -d"

bspc monitor -d I II III IV V VI

bspc config border_width          3
bspc config window_gap           16
bspc config bottom_padding          65

bspc config normal_border_color "#000000"
bspc config focused_border_color "#1F8999"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"
#
bspc config automatic_scheme     alternate
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config history_aware_focus   true
bspc config focus_by_distance     true

bspc config split_ratio          0.43

bspc rule -a Zathura state=tiled
bspc rule -a FloatThis state=floating
bspc rule -a mpv state=floating center=true
bspc rule -a feh state=floating center=true
bspc rule -a photoqt state=floating center=true
