[main]
include=~/.config/foot/theme.ini

font=PragmataPro Mono:size=8
font-bold=JetBrains Mono NL NerdFont:bold:size=8
font-italic=JetBrains Mono NL NerdFont:size=8
font-bold-italic=JetBrains Mono NL NerdFont:size=8
line-height=12

shell=/bin/zsh
term=xterm-256color
login-shell=yes
font-size-adjustment=1px
box-drawings-uses-font-glyphs=no
dpi-aware=yes
pad=8x8 center
bold-text-in-bright=yes

[scrollback]
lines=10000

[colors-dark]
foreground=d0d0d0
background=111111
regular0=1c1c1c
regular1=ff5f5f
regular2=5faf5f
regular3=5f5f00
regular4=87afff
regular5=8787af
regular6=5f8787
regular7=d0d0d0
bright0=8a8a8a
bright1=ff5f5f
bright2=5fd75f
bright3=5f5f00
bright4=87afff
bright5=8787af
bright6=5fafaf
bright7=ffffff

[colors-light]
background=ffffff
foreground=000000
regular0=000000
regular1=a60000
regular2=005e00
regular3=813e00
regular4=0031a9
regular5=721045
regular6=00538b
regular7=bfbfbf
bright0=595959
bright1=972500
bright2=315b00
bright3=70480f
bright4=2544bb
bright5=5317ac
bright6=005a5f
bright7=ffffff

selection-foreground=ffffff
selection-background=005f87
cursor=ff0000 aa0000

alpha=1
blur=true

[key-bindings]
clipboard-copy=Mod4+c XF86Copy
clipboard-paste=Mod4+v XF86Paste
spawn-terminal=Mod4+n

[tweak]
box-drawing-base-thickness=0.01

# vim: ft=dosini
